/**
 * Every shape that crosses the network, in one package.
 *
 * Imported by route handlers on the server and by components on the client, so
 * nothing in here may import `@orientation/db`, `next`, or anything with a
 * runtime that does not belong in a browser bundle. The only dependency is Zod.
 *
 * Requests are Zod schemas and are validated at runtime. Responses are plain
 * types and are not — see the note at the top of `common.ts` for why.
 */
export {
  API_ERROR_CODES,
  ERROR_STATUS,
  broadcastAudience,
  broadcastPriority,
  code10,
  companionRelationship,
  cuid,
  formNumber,
  pageQuery,
  parseInput,
  passStatus,
  personName,
  phone10,
  reference,
  registrationStatus,
  role,
  scanMethod,
  scanOutcome,
  type ApiError,
  type ApiErrorCode,
  type BroadcastAudience,
  type BroadcastPriority,
  type CompanionRelationship,
  type Page,
  type PageQuery,
  type ParseOutcome,
  type PassStatus,
  type RegistrationStatus,
  type Role,
  type ScanMethod,
  type ScanOutcome,
} from './common'

export {
  MAX_COMPANIONS,
  SELFIE_MAX_BYTES,
  SELFIE_MIME_TYPES,
  companionInput,
  companionsInput,
  draftData,
  draftSaveRequest,
  helpDeskQuery,
  lookupRequest,
  selfieDataUrl,
  selfieInput,
  selfieReplaceRequest,
  submitRequest,
  type AdmittedStudentPreview,
  type CompanionInput,
  type CompanionSummary,
  type DraftData,
  type DraftResponse,
  type DraftSaveRequest,
  type HelpDeskQuery,
  type LookupRequest,
  type LookupResponse,
  type MeResponse,
  type PassSummary,
  type SelfieInput,
  type SelfieReplaceRequest,
  type SelfieReplaceResponse,
  type SubmitRequest,
  type SubmitResponse,
} from './registration'

export {
  ROSTER_EXTENSIONS,
  ROSTER_MAX_BYTES,
  ROSTER_MIME_TYPES,
  RETAKE_REASONS,
  adjustQrLifeRequest,
  auditQuery,
  broadcastRequest,
  cloudinaryAddRequest,
  cloudinaryUpdateRequest,
  exportQuery,
  gateUpdateRequest,
  manualCheckInRequest,
  moderationQueueQuery,
  registrationListQuery,
  restorePassRequest,
  retakeReasonCode,
  reverseCheckInRequest,
  reviewRequest,
  revokePassRequest,
  rosterCommitRequest,
  rosterRollbackRequest,
  roleGrantRequest,
  settingsUpdateRequest,
  userStatusRequest,
  type AdjustQrLifeRequest,
  type AdjustQrLifeResponse,
  type AuditEntryView,
  type AuditQuery,
  type BroadcastRequest,
  type BroadcastView,
  type CloudinaryAddRequest,
  type CloudinaryConfigView,
  type CloudinaryPrimaryView,
  type CloudinaryUpdateRequest,
  type ExportQuery,
  type GateUpdateRequest,
  type GateView,
  type ManualCheckInRequest,
  type ModerationItem,
  type ModerationQueueQuery,
  type RegistrationDetailView,
  type RegistrationListQuery,
  type RegistrationRow,
  type RestorePassRequest,
  type RetakeReasonCode,
  type ReverseCheckInRequest,
  type ReviewRequest,
  type ReviewResponse,
  type RevokePassRequest,
  type RoleGrantRequest,
  type RosterCommitRequest,
  type RosterCommitResponse,
  type RosterImportView,
  type RosterIssueView,
  type RosterPreviewResponse,
  type RosterRollbackRequest,
  type RosterRollbackResponse,
  type RosterSampleRow,
  type SettingsResponse,
  type SettingsUpdateRequest,
  type StaffView,
  type StatsResponse,
  type UserStatusRequest,
  type UserStatusResponse,
} from './admin'

export {
  MANIFEST_MAX_AGE_MS,
  MANIFEST_REFRESH_MS,
  deviceHelloRequest,
  deviceId,
  manifestQuery,
  scanEventInput,
  scannerLookupQuery,
  selfieRequestParams,
  syncRequest,
  type DeviceHelloRequest,
  type DeviceHelloResponse,
  type ManifestKey,
  type ManifestPass,
  type ManifestQuery,
  type ManifestResponse,
  type ScanEventInput,
  type ScannerLookupQuery,
  type ScannerLookupResponse,
  type SelfieResponse,
  type SelfieRequestParams,
  type SyncEventResult,
  type SyncRequest,
  type SyncResponse,
} from './scanner'
